Make tests compatible with go1.15
This fixes the following errors:

	# github.com/u-root/u-root/pkg/tss
	pkg/tss/capabilities.go:48:17: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
	pkg/tss/capabilities.go:48:51: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
	pkg/tss/capabilities.go:48:83: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
	pkg/tss/capabilities.go:48:113: conversion from uint32 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

	# github.com/u-root/u-root/cmds/core/elvish/eval
	cmds/core/elvish/eval/exception.go:196:10: Sprintf format %v with arg f causes recursive Error method call

	--- FAIL: TestUptime/badDataInput (0.00s)
        uptime_test.go:34: Mismatched Error returned :got error time: invalid duration "strings" ,want error time: invalid duration strings

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>