fs_test: skip TestFSGoodFile is not run as root.
...as cleanup temporary folder can require root
after we temper with file I node flags.

e.g.

```
--- FAIL: TestFSGoodFile (0.00s)
    testing.go:967: TempDir RemoveAll cleanup: unlinkat /tmp/TestFSGoodFile214938004/001/x: operation not permitted
FAIL
```

Signed-off-by: David Hu <xuehaohu@google.com>