pkg/ldd: add build constraints
go get github.com/u-root/u-root on darwin fails with

  # github.com/u-root/u-root/pkg/ldd
  u-root/u-root/pkg/ldd/ldd_unix.go:156:18: undefined: LdSo

Fix this by adding build constraints for freebsd and linux which are
currently the only supported platforms for pkg/ldd

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>